// Code generated by mockery v2.29.0. DO NOT EDIT.

package mocks

import (
	homestay "github.com/GroupProject3-Kelompok2/BE/features/homestay"
	mock "github.com/stretchr/testify/mock"
)

// HomestayServiceInterface is an autogenerated mock type for the HomestayServiceInterface type
type HomestayServiceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: input
func (_m *HomestayServiceInterface) Create(input homestay.HomestayCore) error {
	ret := _m.Called(input)

	var r0 error
	if rf, ok := ret.Get(0).(func(homestay.HomestayCore) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewHomestayServiceInterface interface {
	mock.TestingT
	Cleanup(func())
}

// NewHomestayServiceInterface creates a new instance of HomestayServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewHomestayServiceInterface(t mockConstructorTestingTNewHomestayServiceInterface) *HomestayServiceInterface {
	mock := &HomestayServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
