// Code generated by mockery v2.30.1. DO NOT EDIT.

package mocks

import (
	reservation "github.com/GroupProject3-Kelompok2/BE/features/reservation"
	mock "github.com/stretchr/testify/mock"
)

// ReservationServiceInterface is an autogenerated mock type for the ReservationServiceInterface type
type ReservationServiceInterface struct {
	mock.Mock
}

// Create provides a mock function with given fields: input
func (_m *ReservationServiceInterface) Create(input reservation.ReservationCore) error {
	ret := _m.Called(input)

	var r0 error
	if rf, ok := ret.Get(0).(func(reservation.ReservationCore) error); ok {
		r0 = rf(input)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewReservationServiceInterface creates a new instance of ReservationServiceInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewReservationServiceInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *ReservationServiceInterface {
	mock := &ReservationServiceInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
