// Code generated by mockery v2.29.0. DO NOT EDIT.

package mocks

import (
	review "github.com/GroupProject3-Kelompok2/BE/features/review"
	mock "github.com/stretchr/testify/mock"
)

// ReviewService is an autogenerated mock type for the ReviewService type
type ReviewService struct {
	mock.Mock
}

// AddReview provides a mock function with given fields: userId, request
func (_m *ReviewService) AddReview(userId string, request review.ReviewCore) error {
	ret := _m.Called(userId, request)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, review.ReviewCore) error); ok {
		r0 = rf(userId, request)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewReviewService interface {
	mock.TestingT
	Cleanup(func())
}

// NewReviewService creates a new instance of ReviewService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewReviewService(t mockConstructorTestingTNewReviewService) *ReviewService {
	mock := &ReviewService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
